CREATE TABLE `usuario` (
 `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `cidade` VARCHAR(255) DEFAULT NULL,
 `nome` VARCHAR(255) NOT NULL,
 `telefone` VARCHAR(255) DEFAULT NULL,
 `TipoUsuario` ENUM('MEDICO', 'PACIENTE', 'ADMIN') DEFAULT NULL
);
